name: FirstWorkflow
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:

    linter_job:
    
       runs-on: ubuntu-latest
       
       steps:
         - name: Run a one-line script
           run: echo "Job start"

         
         - name: "checkout"
           uses: actions/checkout@v2
       
         - name: ktlint
           uses: ScaCap/action-ktlint@master

         - name: Run a one-line script
           run: echo "Job end"
