name: FirstWorkflow

on:
    push:
      branches: [ "main" ]
      paths:
          - "**/*.kt"
          - ".github/workflows/ktlint.yml"
    pull_request:
      branches: [ "main" ]
      paths:
          - "**/*.kt"
          - ".github/workflows/ktlint.yml"

jobs:

    linter_job:
    
       runs-on: ubuntu-latest
       
       steps:
         - name: Run a one-line script
           run: echo "Job start"

         - uses: actions/setup-java@v3
           with:
              distribution: "adopt"
              java-version: "11"
  
         - name: Setup Gradle
           uses: gradle/gradle-build-action@v2
    
         - run: ./gradlew ktlintCheck
         
         - name: "checkout"
           uses: actions/checkout@v2
       
         - name: Ktint set up
           run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.50.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/

         - run: ktlint '!**/build/**'

         - name: Run a one-line script
           run: echo "Job end"
