name: FirstWorkflow
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:

    linter_job:
    
       runs-on: ubuntu-latest
       
       steps:
         - name: Run a one-line script
           run: echo "Job start"

         
         - name: "checkout"
           uses: actions/checkout@v2
       
         - name: Ktint set up
           run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.50.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/

         - run: ktlint '!**/build/**'

         - name: Run a one-line script
           run: echo "Job end"
