name: FirstWorkflow
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    release: 
      branches: [ "main" ]

jobs:
    linter_job:
       runs-on: linux-latest
       steps:
         - name: Run a one-line script
           run: echo "Job start"
         
         - uses: actions/checkout@v3
       
         - uses: vroy/gha-kotlin-linter@v4
           with:
             patterns: '*.kt'

         - name: Run a one-line script
           run: echo "Job end"
