name: FirstWorkflow
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    release: 
      branches: [ "main" ]

jobs:
    linter_job:
       runs-on: ubuntu-latest
       steps:
         - name: Run a one-line script
           run: echo "Job start"
         
         - uses: actions/checkout@v3
       
         - name: "ktlint"
           uses: vroy/gha-kotlin-linter@v4
           with:
              name: app
              path: app/build/reports/lint-results-debug.html

         - name: Run a one-line script
           run: echo "Job end"
